### PR TITLE
Configurable salt / hash length

### PR DESCRIPTION
**Pull request by naude-r**
This PR allows the user to choose custom salt / hash lengths as required.

### CODE REVIEW

**Comment by phxql** [comment]
Thank you very much!

**Comment by naude-r** [comment]
@phxql No problem. Would it be possible to release 1.2, or do you have more changes planned?

**Comment by phxql** [comment]
I'll update the Windows binaries and release a 1.2 today evening.

**Comment by naude-r** [comment]
Thank you. Much appreciated!

**Comment by phxql** [comment]
Released version 1.2.

**Comment by naude-r** [comment]
Thank you.

**Pull request merged**
