### PR TITLE
Feature/argon2 m1 lib

### PR DESCRIPTION
**Pull request by cricketsamya**
I have added the dylib built on M1 mac.
Please let me know, if you need more help

### CODE REVIEW

**Comment by phxql** [comment]
Thanks a lot!

**Comment by phxql** [comment]
Could you run https://github.com/phxql/jna-info on your M1 Mac? 

It should output something like:

```
nativeLibraryResourcePrefix: linux-x86-64
Testing JNA... success
```

I'm interested in the `nativeLibraryResourcePrefix` on your M1 machine.

**Comment by cricketsamya** [comment]
> Configure project :
The compile configuration has been deprecated for dependency declaration. This will fail with an error in Gradle 7.0. Please use the implementation configuration instead. Consult the upgrading guide for further information: https://docs.gradle.org/6.8.2/userguide/upgrading_version_5.html#dependencies_should_no_longer_be_declared_using_the_compile_and_runtime_configurations
        at build_8tbbvgm48i7x9dgaeqweqbvrq$_run_closure2.doCall(/Users/sameer.kulkarni/Developement/workspaces/jna-info/build.gradle:17)
        (Run with --stacktrace to get the full stack trace of this deprecation warning.)

> Task :run
nativeLibraryResourcePrefix: darwin
Testing JNA... success

BUILD SUCCESSFUL in 1s
2 actionable tasks: 1 executed, 1 up-to-date
➜  jna-info git:(master)

**Comment by phxql** [comment]
Thanks!

This is indeed interesting, as it seems that JNA can't find the architecture suffix on your System.

This JNA PR (https://github.com/java-native-access/jna/pull/1297) has been merged, but has not been released yet. Support for M1 is therefore incomplete until the new JNA version is released.

**Comment by cricketsamya** [comment]
@phxql Currently I have made a work around on certain calls! I am using a different library for now. But this is really interesting. I hope they release it soon, so you can do it as well! Until then lets wait!

**Pull request merged**
